### ISSUE TITLE
OpenAI Chat Service classes should support function calling and other API updates

### ISSUE THREAD

**Issue by awharrison-28** [microsoft/semantic-kernel#1450]
OpenAI just released new features to the chat completion API. 

https://openai.com/blog/function-calling-and-other-api-updates

Our chat services objects should accommodate these updates. 
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/2315
- [ ] https://github.com/microsoft/semantic-kernel/issues/2932
- [ ] https://github.com/microsoft/semantic-kernel/issues/3017
- [ ] Explore kernel integration with function calling execution
- [ ] Add telemetry for function calling feature
```

**Comment by gmilano** [comment]
Do you have some plan on how to implement this ? 

The sk has a dependency with azure sdk, the current implementation rely on Azure SDK event for abstract chat concepts,  for example on the Azure.AI.OpenAI.ChatRole class, are you thinking to wait for this  https://github.com/Azure/azure-sdk-for-net/issues/37013 ?

I think that should be better to have the model for chatting without dependencies with any other external library, so that different services provider (OpenAI, Azure Open AI or any other provider) can evolve at their own rythm.

**Comment by daxian-dbw** [comment]
The latest release of the [Azure.AI.OpenAI](https://www.nuget.org/packages/Azure.AI.OpenAI/1.0.0-beta.6) already supports [Chat Functions](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.OpenAI_1.0.0-beta.6/sdk/openai/Azure.AI.OpenAI/README.md#use-chat-functions). Can someone please share the plans on how this feature will be accommodated to Semantic Kernel (especially, the planner)?

**Comment by samleegithub** [comment]
Just saw that too. Here is the blog post announcing this yesterday: https://techcommunity.microsoft.com/t5/azure-ai-services-blog/function-calling-is-now-available-in-azure-openai-service/ba-p/3879241

This would greatly improve the reliability of planners in SK in generating JSON.

**Comment by hooyao** [comment]
What's the difference between SK's planner + custom skills and function calling?

**Comment by eavanvalkenburg** [comment]
Just created a first implementation for this #2356

**Comment by Kevdome3000** [comment]
What's the status on the dotnet implementation? I've done my own and if there isn't any plan on for this on the teams end I can submit a PR

**Comment by daxian-dbw** [comment]
@eavanvalkenburg and @Kevdome3000, can both of you please give a summary on how you are leveraging the function calling in your implementation? Like, what improvement does it bring to semantic kernel in your minds?

IMHO, the function calling, to some extent, makes semantic functions less necessary. As a user, I'd like to use native functions with function calling, and having semantic kernel to handle all the argument validation and invocation behind the scene (custom validation is optional and should be allowed). Of course, API should be exposed to let the user choose whether to run a function during the chat completion.

**Comment by daxian-dbw** [comment]
- This is the LangChain issue thread about supporting function calling: https://github.com/langchain-ai/langchain/issues/6196
- This is an example of using function calling in a LangChain agent: https://python.langchain.com/docs/modules/agents/agent_types/openai_functions_agent

I reference them here in the hope that they can inspire the design in Semantic Kernel to incorporate the OpenAI function calling feature.

LangChain get the function calling integrated soon after the feature was announced. I think the Semantic Kernel team should move faster on this work.

**Comment by alexminza** [comment]
@awharrison-28 is there a specific branch to track the development of this feature for C# / .NET?

**Comment by Kevdome3000** [comment]
@daxian-dbw here is a rough implementation: https://github.com/microsoft/semantic-kernel/pull/2597. Happy to collab on improvements

**Comment by gitri-ms** [comment]
Hi all -- I'm the SK engineer working on the .NET implementation. Sorry for the silence here, it's been a crazy busy couple of weeks, so I hadn't made a lot of traction on it yet. Thanks @Kevdome3000 for kickstarting the .NET effort with your PR! I will take a look through in a bit and see how it aligns with what we were thinking. 

From the SK team's perspective, it's important we maintain a consistent architecture between the Python and .NET implementations (and any future language implementations as well), so I am working to capture design decisions in an [ADR](https://github.com/microsoft/semantic-kernel/tree/main/docs/decisions) over the next few days, as we align the implementations and get them closer to check-in ready.

**Comment by d3r3kk** [comment]
Java will revisit this post-beta (October).

**Comment by aaronpowell** [comment]
Just wanting to jump in here and add another scenario to where function calling is useful.

I'm building a demo app where we're indexing video transcripts for searching (via vectors) and then using the results in chat completions.

If we start with a user-provided prompt like:

> Find me sessions on leadership

We could get back a list of say five but there could be more, and the completion alludes to that. So the user would want to do a new prompt like:

> Give me the next 5

Now we've got a branch in our logic, we're wanting to re-execute the original prompt but when we query the memory store we use an offset of five so that we can give more results. And this is where functions would be useful. We'd have two functions, `get_sessions` and `get_more_sessions`, then when we do the initial completion we'd get back a function name that tells us which to call and then we execute the right pipeline.

I've got some working demos of this app (both in .NET and Python) to demonstrate if that'd be of help.

**Comment by gitri-ms** [comment]
Hi all, thank you again for your perspectives and the explorations/implementations for this feature!

We on the SK team have been having in-depth design discussions to determine how this capability fits into the greater architectural vision for SK. These conversations are still ongoing, and we are evaluating several different approaches and design questions (including those presented through the PRs linked here).

I hope to have more clarity on the architectural direction we want to take within the next week, so until then I am marking both PRs as draft and will follow up. Thanks again for the great conversations here.

**Comment by douglasware** [comment]
@Kevdome3000 very nice work! Thanks.

**Comment by gitri-ms** [comment]
Hello everyone, thanks for your patience with this! I've got a draft PR for an alternative .NET approach here: https://github.com/microsoft/semantic-kernel/pull/2842. Feel free to take a look!

Since this feature is only supported for OpenAI, we are trying to contain changes to the OpenAI connector as much as possible. This approach keeps the door open to add planners around this feature in the future. I am still working to tie up some loose ends, capture all our design decisions, and add validation/tests.

**Comment by bgbbmm** [comment]
Anxiously awaiting the new preview package to be pushed out. I saw the nightly builds included this update but none of those packages are actually available on nuget. I'm hoping to demo this functionality for a presentation I am doing in 9 days! Seems like the weekly pre-release skipped a week so really hoping one is created this week and soon. Thanks for your hard work!

**Comment by matthewbolanos** [comment]
Thanks @bgbbmm for your interest in this new feature. The Semantic Kernel team is prepping for its v1.0.0 release which will include many breaking changes as we improve the interface. Because of the number of breaking changes, we'll be skipping one additional week before providing our v1.0.0.RC1 release on Monday (10/9).

If you are interested in using the nightly build in your existing project, I'd recommend pulling it down with the following command `dotnet add package Microsoft.SemanticKernel --version 0.26.231003.1-nightly`. Thank you for your patience as we prep for v1.0.0.

**Comment by bgbbmm** [comment]
@matthewbolanos Thanks for responding Matthew. I had actually tried to add the nightly build package a few days ago, but I got an error stating the package didn't exist/could not be found. When I looked in nuget I also didn't see any of the nightly packages either.

**Comment by bgbbmm** [comment]
I just realized my mistake with this. I was only looking in nuget.org.

**Comment by dmytrostruk** [comment]
Hi @bgbbmm ! 
We created draft PR with instructions how to access nightly builds: https://github.com/microsoft/semantic-kernel/pull/3061
Please let us know if that helps. Thank you!

**Comment by bgbbmm** [comment]
Thank you both. I was able to add this package yesterday with the same style of command.

I was surprised to see the number of breaking changes between the previous release and the nightly build, so I now understand why you've held off. Thanks and I can't wait to build something really useful with these functions!

**Comment by bgbbmm** [comment]
Using today's nightly build I was looking at the example Example59_OpenAIFunctionCalling.

Locally I tried to copy and run this to see how it worked, however the method "ImportPluginFunctionsAsync" doesn't appear to exist. There is a function "ImportAIPluginAsync" which seems similar, but if I try to use that then I see a compile error stating: "Reference to type 'ISKFunction' claims it is defined in 'Microsoft.SemanticKernel.Abstractions', but it could not be found"

Anyone have thoughts on this?

**Comment by gitri-ms** [comment]
@bgbbmm This sample takes a dependency on [`Microsoft.SemanticKernel.Functions.OpenAPI`](https://github.com/microsoft/semantic-kernel/pkgs/nuget/Microsoft.SemanticKernel.Functions.OpenAPI) since it imports the Klarna plugin to use in the example. In the latest package, `ImportPluginFunctionsAsync` replaces `ImportAIPluginAsync`, as the latter is being deprecated to align to our new naming scheme. It seems like you might not have the latest version of that package.

To fix this, you have a few options:
1. Replace `ImportPluginFunctionsAsync` with `ImportAIPluginAsync` in the example code (the functionality is the same)
2. Get the latest nightly build of `Microsoft.SemanticKernel.Functions.OpenAPI`
3. Remove the dependency on `Microsoft.SemanticKernel.Functions.OpenAPI` by commenting out the line that imports the Klarna plugin

Hope that helps.

**Comment by bgbbmm** [comment]
> @bgbbmm This sample takes a dependency on the [`Microsoft.SemanticKernel.Functions.OpenAPI`](https://github.com/microsoft/semantic-kernel/pkgs/nuget/Microsoft.SemanticKernel.Functions.OpenAPI) package since it imports the Klarna plugin to use in the example. In the latest package, `ImportPluginFunctionsAsync` replaces `ImportAIPluginAsync`, as the latter is being deprecated to align to our new naming scheme. It seems like you might not have the latest version of that package.
> 
> To fix this, you have a few options:
> 
> 1. Get the latest nightly build of `Microsoft.SemanticKernel.Functions.OpenAPI`
> 2. Keep the version you have, and replace `ImportPluginFunctionsAsync` with `ImportAIPluginAsync` in the example code (the functionality is the same)
> 3. Remove the dependency on `Microsoft.SemanticKernel.Functions.OpenAPI` by commenting out the line that imports the Klarna plugin
> 
> Hope that helps.

Yes thank you, I did not realize there was a missing dependency. Thank you for the explanation and clarification on the updated naming conventions.
