### ISSUE TITLE
SequentialPlanner support in KernelHttpServer + Book Creator Sample App

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#1643]
```[tasklist]
### Tasks
- [ ] Check with Matthew on what we're trying to showcase with sample apps
- [ ] Add option to use SequentialPlanner in KernelHttpServer
- [ ] Change CreateBookWithPlanner in book creator sample app to parse ambiguous results
```

**Comment by matthewbolanos** [comment]
Closing since this sample no longer exists.
