### ISSUE TITLE
CC: UX improvements

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#1644]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/1642
- [ ] https://github.com/microsoft/semantic-kernel/issues/1645
- [ ] https://github.com/microsoft/semantic-kernel/issues/1646
```
