### ISSUE TITLE
CC: Store User ID instead of username / email in ChatMessage and MemorySource

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#1646]
Currently we are storing user information that is considered PII in ChatMessage and MemorySource.
We need to perform real-time look up using User IDs instead for privacy concerns. 

This should also address the problem where the list of participants shows a GUID instead of the user's name and profile picture.

PRs that need to have this improvment:
https://github.com/microsoft/semantic-kernel/pull/1345
https://github.com/microsoft/semantic-kernel/pull/1307
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/pull/1899
- [ ] Remove username instances from store in webapi + do real time on chat history load in webapp
- [ ] Load user photos from Graph
```
