### ISSUE TITLE
C# Kernel: Add End-to-End Telemetry

### ISSUE THREAD

**Issue by evchaki** [microsoft/semantic-kernel#1651]
Leverage ILogger with Azure Monitor (AppInsights) to send custom telemetry for the following:

1.	Ask (disabled by default) – the actual Ask (text) coming into the Kernel from the application (example: “Create an email to my boss with a summarization of this ......”  this will be important in Dev and maybe UAT/test environments.  But for PII in production it should be disabled

2.	Planner (enabled by default) – this is the planner step (either using one of our planners or if the developer hard coded in a plan
     a.	Ideal information to store here: Execution time, Model used for planner, success state (Success / Failed), Plan returned, total tokens used

3.	Steps executed for the returned plan (enabled by default)
      a.	Ideal information to store here: Plugin executed, execution time, success state (Success / Failed), Tokens used, Model used, Plan this was run from

4.	Kernel Errors throughout the process 
      a.	Critical, Failures, Warnings – (enabled by default)
      b.	Non-fatal (disabled by default)

```[tasklist]
### Tasks
- [x] Telemetry for Ask
- [x] Telemetry for Planner
- [x] Telemetry for plan execution
- [x] Telemetry for Kernel errors
- [x] Samples and demos with telemetry usage
```

**Comment by dmytrostruk** [comment]
Telemetry for Kernel errors will be handled after exception handling issue is closed: https://github.com/microsoft/semantic-kernel/issues/1669

**Comment by torronen** [comment]
Can we have a clear documentation or warning, and disabling of telemetey, especially for the prompt? To me it sounds like playing with fire (EU GDPR with heavy fines)

r

**Comment by alexminza** [comment]
LangSmith is a great tool that builds on top of this type of functionality https://github.com/microsoft/semantic-kernel/issues/2070
