### ISSUE TITLE
Error handling [Parent Issue]

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#1669]
```[tasklist]
### Tasks
- [x] 1.Requirements gathering
- [x] 2.Requirements analysis and design
- [x] 3.Design/ADR
- [x] 4.Replace SK custom exceptions by SKException or one of its derivatives
- [x] 5.Use HttpOperationException in all components using HTTP
- [x] 6.Remove the wrapping of exceptions for the sake of wrapping
- [x] 7.Modify methods of Kernel, SKFunction and Planner classes to throw exceptions
```

**Comment by SergeyMenshykh** [comment]
List of PRs:
- https://github.com/microsoft/semantic-kernel/pull/2263
- https://github.com/microsoft/semantic-kernel/pull/2298
- https://github.com/microsoft/semantic-kernel/pull/2299
- https://github.com/microsoft/semantic-kernel/pull/2362
- https://github.com/microsoft/semantic-kernel/pull/2468
- https://github.com/microsoft/semantic-kernel/pull/2494
- https://github.com/microsoft/semantic-kernel/pull/2546
- https://github.com/microsoft/semantic-kernel/pull/2622
- https://github.com/microsoft/semantic-kernel/pull/2672
- https://github.com/microsoft/semantic-kernel/pull/2721
