### ISSUE TITLE
.Net: Document how to use remote plugin manifests with Semantic Kernel

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#1728]
Kernel should be able to execute plugins that are not registered in the kernel but are pulled dynamically from a vector store.

Developers do not always have access to the kernel code or access to change it.  Plugin developers will need to be able to create their plugins and deploy those.  After they do that, they will use the manifest file with the description in it to store into a centralized location.  This location will need to be fast to query and retrieve plugins that will help solve the ask.
```[tasklist]
### Tasks
- [x] Update SequentialPlanner to allow ability to specific available functions and load functions on demand.
- [ ] Define PluginManifest naming and schema
- [ ] Enable kernel to import a PluginManifest
- [ ] Update StepwisePlanner
- [ ] Update ActionPlanner
```

**Comment by matthewbolanos** [comment]
We'll first start by adding documentation that shows how to do this today.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
