### ISSUE TITLE
Copilot Chat: Add ChatGPT plugin to Copilot

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#1973]
```[tasklist]
### Tasks
- [ ] Add Open API Spec verification (see PluginUtils.ts)
- [ ] Add error handling if plugin isn't validated
- [ ] Add manifest details to ValidateStep
```

**Comment by teresaqhoang** [comment]
Closing in favor of: https://github.com/orgs/microsoft/projects/852/views/1?pane=issue&itemId=34679748
