### ISSUE TITLE
.Net: Rename 'Skills' -> 'Plugins'

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2119]
```[tasklist]
### Tasks
- [x] .Net: Skill->Plugins: Existing skills Nuget packages and direct dependants
- [x] .Net: Skill->Functions: GRPC and OpenAPI Nuget packages and direct dependants
- [x] .Net: Skill->Plugins: SK Core and Abstractions
- [x] .Net: Skill->Plugins: Update integration tests
- [x] .Net: Skill->Plugins: Update sample skills and examples
- [ ] https://github.com/microsoft/semantic-kernel/issues/2970
- [ ] .Net: Skill->Plugins: Update Matthews document
- [ ] https://github.com/microsoft/semantic-kernel/issues/2127
- [ ] https://github.com/microsoft/semantic-kernel/pull/2943
- [ ] https://github.com/microsoft/semantic-kernel/pull/2937
```

**Comment by markwallace-microsoft** [comment]
Done
