### ISSUE TITLE
.Net: Control logic in pre/post- hooks: Phase 2

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2324]
> [!IMPORTANT]  
> Labeled **Urgent** because it will require a breaking change.

Support events for Plans and Prompt Rendering

Pre-Invocation event:
  - See trace of what functions came before (TBD) 
    i.e. for TrustService 
 
  - Semantic functions:
    - See model/endpoint to be used

  - Actions:
    - Modify prompt (TBD)
 
In-Invocation event: (TBD)
  - Get output StreamReader

Post-Invocation event:
  - Get state succeded / faulted + details

  - Actions
    - Stop execution
    - Repeat step
    - Set next step/branch in the plan

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/pull/2903
- [x] Change Prompt Template Engine impl to use Executor.ExecuteAsync()
- [ ] Change Plans to use Executor.ExecuteAsync()
- [ ] Update PrePost hooks examples and implementations to suffice this Issue completely
```

**Comment by RogerBarreto** [comment]
This one will be partially addressed by the #1714 and the existing PR #2045.

**Comment by RogerBarreto** [comment]
Update the description only with Features related to Phase 2.

**Comment by RogerBarreto** [comment]
This one will be partially addressed by the #2846

**Comment by markwallace-microsoft** [comment]
Removing from V1 RC1 as this cannot be contained
