### ISSUE TITLE
Context Sample: Intro

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#2342]
```[tasklist]
### Tasks
- [x] Write sample code
- [x] Write readme instructions
- [x] Write accompanying learn doc (may be separate PR?)
- [x] Edit learn doc
- [x] Test on Azure OpenAI supported models
- [x] Test on OpenAI supported models
- [x] Incorporate feedback
- [x] Publish
```

PR draft: https://github.com/MicrosoftDocs/semantic-kernel-pr/pull/151

**Comment by momuno** [comment]
code and initial readmes are in PR draft here: https://github.com/MicrosoftDocs/semantic-kernel-pr/pull/151
working through readme approach.  may be revisited later after publish.  may separate learn doc to different PR.

**Comment by momuno** [comment]
code and readme complete (unless any other small feedback to incorporate).
in progress of completing learn doc on context intro.

**Comment by momuno** [comment]
.NET version published.
