### ISSUE TITLE
.Net: Feature: Add extenstion for Azure OpenAI On Your Data

### ISSUE THREAD

**Issue by mayashavin** [microsoft/semantic-kernel#2392]
**Description:**

- Azure OpenAI has a new service called Azure OpenAI On Your Own Data which allows to have a chat completion on a specific customer's datasource (mainly with Azure Cognitive Search). We want to be able to add this capability as an extension to AzureOpenAI connector for SK.

- Currently it only supports using the API (preview mode) in Playground or REST API, and there should be a C# SDK
support soon.
- This feature will allow user to ask/query a question on a set of documents and receive relevant answer + citations.

Supporting links: 
https://learn.microsoft.com/en-us/azure/ai-services/openai/use-your-data-quickstart?tabs=command-line&pivots=rest-api
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data

**Related issue**: #2326 

**Feature proposal:**

- Add another extension `WithAzureOnYourDataChatCompletion` to `OpenAIKernelBuilderExtensions` that allows user to use the Azure OpenAI On Your Data with SK.
- Currently will integrate the service with the relevant REST API under the hood. Can be upgraded to the official Azure.OpenAI SDK method when it's relevant.

We already did a small custom extension on our project to have this capability enabled in our usage of SK. Will be happy to make a PR if it makes sense.

```[tasklist]
### Tasks
- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] Add unit tests without breaking anything
- [ ] Add example
```

**Comment by nacharya1** [comment]
@mayashavin - thanks for letting us know. This is something we are actively working on see #2326
