### ISSUE TITLE
Feature: Add Azure Form Recognizer as a Skill to process document

### ISSUE THREAD

**Issue by mayashavin** [microsoft/semantic-kernel#2399]
**Description**

- Add Form Recognizer as a Skill to process document into structured data, ready for chunking/embedding using other AI services
```[tasklist]
### Tasks
- [ ] The code builds clean without any errors or warnings
- [ ] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ ] Add unit tests without breaking anything
- [ ] Add example to demonstrate
```

**Comment by evchaki** [comment]
@mayashavin - this is a great suggestion.  Can you make this into a OpenAI / Microsoft Plugin format?  Here are some links to get you started:

- CONTRIBUTING - https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md
- Testing a Plugin - https://devblogs.microsoft.com/semantic-kernel/test-your-chatgpt-plugins-in-the-updated-chat-copilot/
- Creating a Plugin - https://devblogs.microsoft.com/semantic-kernel/create-your-first-chatgpt-plugin-for-semantic-kernel/

**Comment by mayashavin** [comment]
> @mayashavin - this is a great suggestion. Can you make this into a OpenAI / Microsoft Plugin format? Here are some links to get you started:
> 
> * CONTRIBUTING - https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md
> * Testing a Plugin - https://devblogs.microsoft.com/semantic-kernel/test-your-chatgpt-plugins-in-the-updated-chat-copilot/
> * Creating a Plugin - https://devblogs.microsoft.com/semantic-kernel/create-your-first-chatgpt-plugin-for-semantic-kernel/

Absolutely. Will do.

**Comment by dbgoytia** [comment]
Hello @mayashavin, is this issue still available? I'm new in the community and looking to contribute.

**Comment by matthewbolanos** [comment]
Closing this since this issue is a few months old
