### ISSUE TITLE
.Net: Support importing plugins

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2459]
> [!IMPORTANT]  
> Labeled **High** because it will not require a breaking change, but it's important to complete by v1.0.0

**Context:**
Currently, SK reads the `[Description]` attribute off of `SKFunctions` but not Plugins. Additionally, semantic memory is underutilized in the planners when memory has the potential to help mitigate scaling issues when there are many plugins to work with. When the number of functions exceeds the token limits, currently the planners fail. Without pre-filtering the functions, to prevent failure, requests to the LLM would need to be chunked. This adds seconds to plan creation time and therefore won't scale well. 

Additionally, unrelated to planners, the [openapi.yml](https://github.com/openai/plugins-quickstart/blob/main/openapi.yaml) files used by Chat GPT plugins has a description property that would benefit from automation from SK if available.

The goal of this task is to:
- improve plan creation time
- automate filling out the description property of the openapi.yml file

```[tasklist]
### Tasks
- [ ] .Net: Add plugin class to Semantic Kernel
- [ ] .Net: Create a property on IKernel to access plugins objects
- [ ] .Net: Create an ImportPlugin() method for plugin-ai.json files
- [ ] .Net: Create a plugin serialization for semantic/native functions
- [ ] .NET: Create an ImportPlugin() method for semantic/native functions
- [ ] https://github.com/microsoft/semantic-kernel/issues/3233
```

**Comment by hario90** [comment]
I started investigation for this task but didn't implement it in a production-ready way.

I looked into whether including the plugin description attribute improves plan creation quality and speed. 

I found that speed can be improved, especially considering that as the number of plugins grows, the number of requests to the LLM needs to increase unless there's a function pre-filtering step. An LLM request takes 2-3 seconds while a semantic search (sample size around 100) takes around 100 ms. Additionally, some preliminary results from my [speed tests](https://github.com/hario90/semantic-kernel/tree/description-attribute-speed-tests) showed that a smaller function manifest may speed up plan creation.

On the quality side, my results were inconclusive. There may still be potential to improve the accuracy of plan results but I didn't have a good test case to prove this. Once there's support for picking up plugin descriptions, it will be easier to use this within the function manual if that is something that needs to be pursued.

The challenge to pre-filtering plugins is that semantic search may not filter any plugins if your max results returned config value is not small enough. For example, if you rely on minimum relevancy score alone to filter out unrelated plugins, you may be surprised like I was to find that none of your plugins got filtered out.

**Comment by matthewbolanos** [comment]
This is now supported
