### ISSUE TITLE
Semantic Function, Template Engine Extraction from Kernel.Core [Parent Issue]

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2461]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/2527
- [ ] https://github.com/microsoft/semantic-kernel/issues/2563
- [ ] https://github.com/microsoft/semantic-kernel/issues/2570
- [ ] https://github.com/microsoft/semantic-kernel/issues/2624
```

**Comment by nacharya1** [comment]
@markwallace-microsoft - could you please add target dates for this issue.
