### ISSUE TITLE
Feature Suggestion: Consistent Interface for Planners and Configs

### ISSUE THREAD

**Issue by jorisdg** [microsoft/semantic-kernel#2519]
I realize the Stepwise Planner is brand new and perhaps this is in the works already, but it would be nice to have the planners all implement the same interface... similarly, the configs can implement the same interface or inherit an (abstract?) base class or something.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/2847
- [ ] https://github.com/microsoft/semantic-kernel/issues/2911
- [x] [ActionPlanner] Add support for memory filtering config properties
- [ ] https://github.com/microsoft/semantic-kernel/issues/2973
- [ ] https://github.com/microsoft/semantic-kernel/issues/2848
- [ ] https://github.com/microsoft/semantic-kernel/issues/1851
- [ ] https://github.com/microsoft/semantic-kernel/issues/2975
- [ ] https://github.com/microsoft/semantic-kernel/issues/2074
```

**Comment by lemillermicrosoft** [comment]
We had considered this before, would love to hear more thoughts and reasoning. I particularly agree with the configuration being shared but can see some configurations just won't apply to other planners so doesn't make sense.

**Comment by lemillermicrosoft** [comment]
#2802 has started to tackle a piece of this.
