### ISSUE TITLE
Extract template engine from Kernel.Core

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#2527]
Template engine will be moved to it's own project i.e. `Extensions\TemplateEngine`

```[tasklist]
### Tasks
- [x] Create new project and move code
- [ ] Create an ADR to describe the change, project naming and impact for consumers
- [ ] Make required build/pipeline changes
```
