### ISSUE TITLE
Saved Plans + Recall

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2581]
```[tasklist]
### Tasks
- [ ] Design doc + defining requirement
- [ ] Serialize plans using prompt flow
- [ ] Embeddings for each saved plan on user intent + recall
- [ ] Call out stale state of recalled plugin
```

**Comment by teresaqhoang** [comment]
PR to support re-running plans: https://github.com/microsoft/chat-copilot/pull/409/files

**Comment by teresaqhoang** [comment]
Re-opening for Recall work - blocked right now due to some issues with semantic memory doing some weird stuff that is targeting documents; 

It does summarizations and and synthetic memories which are memories that come from multiple documents combined. Looking to port the memory extraction prompts and everything to be in the memory service which will require a lot of design and changes. We will want to integrate memory into the planner but we may want to keep it separate from the memory used for chat.

**Comment by teresaqhoang** [comment]
Moving to backlog in favor due to Scale testing

**Comment by matthewbolanos** [comment]
Closing since this is logic that shouldn't existing in an out-of-the-box planner
