### ISSUE TITLE
Plugin Q&A videos

### ISSUE THREAD

**Issue by momuno** [microsoft/semantic-kernel#2748]
```[tasklist]
### Tasks
- [x] Draft Q list
- [x] Draft A content bullet points
- [x] Review with John
- [x] Set date for recordings with Ross
- [x] Record!
```

**Comment by momuno** [comment]
q list in progress

**Comment by momuno** [comment]
All recordings reviewed, and requested info for publishing sent to Ross. Done here :)
