### ISSUE TITLE
Context Sample: Curation

### ISSUE THREAD

**Issue by momuno** [microsoft/semantic-kernel#2749]
```[tasklist]
### Tasks
- [ ] Write sample code
- [ ] Write readme instructions
- [ ] Write accompanying learn doc (may be separate PR?)
- [ ] Test on Azure OpenAI
- [ ] Test on OpenAI
- [ ] Incorporate feedback
- [ ] Publish
```

**Comment by momuno** [comment]
learn doc started.  Draft PR: https://github.com/MicrosoftDocs/semantic-kernel-pr/pull/156

**Comment by matthewbolanos** [comment]
Closing so we can create new issues to track necessary doc changes later
