### ISSUE TITLE
Update all Sample readme template

### ISSUE THREAD

**Issue by momuno** [microsoft/semantic-kernel#2750]
Updates to the sample readme template.
All samples should match.
```[tasklist]
### Tasks
- [ ] Finalize new template
- [ ] Update samples (add each here)
- [ ] Test samples with new readme (add each here)
- [ ] Publish
```

**Comment by matthewbolanos** [comment]
Closing so we can create new doc issues later.
