### ISSUE TITLE
.Net: Function to Function calling

### ISSUE THREAD

**Issue by nacharya1** [microsoft/semantic-kernel#2825]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/pull/2903
- [x] Update template engine to use RunAsync
- [ ] Remaining InvokeAsync clean
```

**Comment by nacharya1** [comment]
Cross-function discoverability, dependency, access restrictions

**Comment by RogerBarreto** [comment]
Partially resolved by #2903
