### ISSUE TITLE
.Net: Multiple LLM support for semantic functions

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3041]
> [!IMPORTANT]  
> Labeled **Urgent** because it will require a breaking change.

Related issues

- https://github.com/microsoft/semantic-kernel/issues/3034
- https://github.com/microsoft/semantic-kernel/issues/2860

```[tasklist]
### Tasks
- [x] Create an ADR listing the use cases for multiple LLM support
- [x] Add AI service selector for AI services and request settings
- [x] Add sample showing how to create custom AI selector
- [x] Add support for arbitrary service attributes
- [x] Add support so that an IAIServiceSelector can select based on model id
- [x] Add base class for IAIServiceSelector's
- [x] Add better error checking for case where no IAIService can be selected
- [x] Change IAIServiceSelector interface so that it can be easily extended in the future
```

**Comment by markwallace-microsoft** [comment]
PR https://github.com/microsoft/semantic-kernel/pull/3040

**Comment by markwallace-microsoft** [comment]
Last part was resolved by https://github.com/microsoft/semantic-kernel/pull/3415
