### ISSUE TITLE
.Net: Support Azure ML prompt serialization

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3128]
> [!IMPORTANT]  
> Labeled **High** because it will not require a breaking change, but it's very important to complete by v1.0.0

Semantic functions should be able to be defined using the Azure ML specification: https://github.com/Azure/azureml_run_specification/pull/1056/files

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/3041
```

```[tasklist]
### Tasks
- [ ] Support f-string templates
- [ ] Support handlebar templates
- [ ] Provide import method for Azure ML prompt files
```

**Comment by matthewbolanos** [comment]
Closing since this is now possible
