### ISSUE TITLE
Epic: Pre/post hooks

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3130]
> [!NOTE]  
> This issue tracks all of the items necessary for pre/post hooks across all languages.

```[tasklist]
### .Net
- [ ] https://github.com/microsoft/semantic-kernel/issues/2324
- [ ] https://github.com/microsoft/semantic-kernel/issues/3142
```

```[tasklist]
### Python
- [ ] https://github.com/microsoft/semantic-kernel/issues/3038
```

```[tasklist]
### Java
```

**Comment by matthewbolanos** [comment]
Closing since the epic tasks are no longer necessary
