### ISSUE TITLE
Epic: Runtime variable and configuration flow

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3131]
> [!NOTE]  
> This issue tracks all of the items necessary to update the variable and configuration flow across all languages.

```[tasklist]
### .Net
- [ ] https://github.com/microsoft/semantic-kernel/issues/2936
- [ ] https://github.com/microsoft/semantic-kernel/issues/1482
- [ ] https://github.com/microsoft/semantic-kernel/issues/3138
- [ ] https://github.com/microsoft/semantic-kernel/issues/3145
- [ ] https://github.com/microsoft/semantic-kernel/issues/2216
- [ ] https://github.com/microsoft/semantic-kernel/issues/2816
- [ ] https://github.com/microsoft/semantic-kernel/issues/3127
- [ ] https://github.com/microsoft/semantic-kernel/issues/3143
- [ ] https://github.com/microsoft/semantic-kernel/issues/3139
- [ ] https://github.com/microsoft/semantic-kernel/issues/3144
```

```[tasklist]
### Python
```

```[tasklist]
### Java
```

**Comment by matthewbolanos** [comment]
Marking as complete for .net; will create seperate issues for Python and Java
