### ISSUE TITLE
Epic: Semantic function serialization alignment

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3133]
> [!NOTE]  
> This issue tracks all of the items necessary for aligning semantic function serialization with the rest of Microsoft.

```[tasklist]
### .Net
- [ ] https://github.com/microsoft/semantic-kernel/issues/3041
- [ ] https://github.com/microsoft/semantic-kernel/issues/1787
- [ ] https://github.com/microsoft/semantic-kernel/issues/3148
- [ ] https://github.com/microsoft/semantic-kernel/issues/2673
- [ ] https://github.com/microsoft/semantic-kernel/issues/3128
```

```[tasklist]
### Python
```

```[tasklist]
### Java
- [ ] https://github.com/microsoft/semantic-kernel/pull/2417
```

**Comment by matthewbolanos** [comment]
Marking as closed for .NET, will create new issues for Python and Java
