### ISSUE TITLE
Epic: Improve function descriptions for planners

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3137]
> [!NOTE]  
> This issue tracks all of the items necessary for aligning semantic function serialization with the rest of Microsoft.

```[tasklist]
### .Net
- [ ] https://github.com/microsoft/semantic-kernel/issues/2915
- [ ] https://github.com/microsoft/semantic-kernel/issues/3129
- [ ] https://github.com/microsoft/semantic-kernel/issues/3140
- [ ] https://github.com/microsoft/semantic-kernel/issues/1978
```

```[tasklist]
### Python
```

```[tasklist]
### Java
```

**Comment by matthewbolanos** [comment]
Marking as closed for .NET, will create new issues for Python and Java
