### ISSUE TITLE
.Net: Ensure template engine can support f-strings and Handlebars

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3148]
> [!IMPORTANT]  
> Labeled **Urgent** because it may require a breaking change. Please lower the priority if this is not the case.

Need to ensure that the template engine can handle the other template engines SK will need to support in the future: f-strings and handlebars

Definition of Done
- Validate the IPromptTemplateEngine interface and prompt template lifecycle will allow us to add template engine implementations using f-string and Handlebars syntax
- Investigate extending IPromptTemplateEngine interface to support discovery of template variables (this functionality was previously removed)

See: https://github.com/microsoft/semantic-kernel/issues/3115
```[tasklist]
### Tasks
- [x] Define flow for compiling and rendering templates
- [x] Provide a collection of SKFunctions to the template engine from the kernel so it can call them
- [x] Allow a template to be used by multiple kernels with different functions and configuration
- [x] Allow IPromptTemplateFactories to be easily aggregated
```

**Comment by markwallace-microsoft** [comment]
As part of this work support for Handlebars has been included. F-string will come later as needed.
