### ISSUE TITLE
.Net: Remove core plugins from v1.0.0 and make them "samples"

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3161]
Core plugins should be treated as samples. Should consider doing the same for other plugins as well.
```[tasklist]
### Tasks
- [ ] Remove core plugins from meta package
- [ ] Move core plugins to samples
- [ ] Move other plugins to samples (optional)
```

**Comment by markwallace-microsoft** [comment]
We are marking these as experimental instead
