### ISSUE TITLE
.Net: Updates related to renaming

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3605]
```[tasklist]
### Tasks
- [x] Update variable names e.g. skfunction, function, view, ....
- [x] Can `GetMetadata` be made non abstract
- [x] Make properties of `KernelFunction` read only
- [ ] https://github.com/microsoft/semantic-kernel/issues/3703
- [x] public IEnumerable<AIRequestSettings> ModelSettings { get; protected set; }
- [x] It'd be good to add a more descriptive "Gets the model request settings that..." comment that elaborates on what this is and what it's for. We typically try to have the summary be a single sentence and then as much additional information as possible in remarks.
```

**Comment by stephentoub** [comment]
This was done
