### ISSUE TITLE
.Net: SK V1 improvements

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#3646]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/3686
- [ ] https://github.com/microsoft/semantic-kernel/issues/3687
- [ ] https://github.com/microsoft/semantic-kernel/issues/3688
- [ ] https://github.com/microsoft/semantic-kernel/issues/3689
- [ ] https://github.com/microsoft/semantic-kernel/issues/3690
- [x] (Issure Created)(Mark) Move Kernel.RunAsy(pipeline) extension methods to samples.
- [x] **(WIP)**(Sergey) Remove SKContext argument from all the things, pass it nowhere. Delete SKContext.
- [ ] https://github.com/microsoft/semantic-kernel/issues/3691
- [ ] https://github.com/microsoft/semantic-kernel/issues/3692
- [ ] https://github.com/microsoft/semantic-kernel/issues/3693
- [ ] https://github.com/microsoft/semantic-kernel/issues/3694
- [x] Rename "SK" to "Kernel" and ensure consistency in which types use the prefix. Also Prompt instead of Semantic.
- [ ] https://github.com/microsoft/semantic-kernel/issues/3695
- [ ] https://github.com/microsoft/semantic-kernel/issues/3696
- [x] (PR Open)(Stephen) Remove resiliency stuff from SK
- [ ] https://github.com/microsoft/semantic-kernel/issues/3698
- [ ] https://github.com/microsoft/semantic-kernel/issues/3697
- [x] (Done)(Mark) integrate pre/post hooks into KernelFunction.InvokeAsync
- [ ] https://github.com/microsoft/semantic-kernel/issues/3699
- [x] (WIP)(Roger) Multi Modality Abstractions - https://github.com/microsoft/semantic-kernel/issues/3675
```

**Comment by stephentoub** [comment]
@SergeyMenshykh, this can be closed now, right?

**Comment by SergeyMenshykh** [comment]
Yep, closing it now.
