### ISSUE TITLE
.Net: Change KernelFunctionsArgument from string values to object values. Fix marshaling accordingly.

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3692]
```[tasklist]
### Tasks
- [x] 1 Prepare public API surface(Change KernelArguments value type to object? + add string value checks)
- [x] 2 Support object? type by OpenAPI(RestAPIOperationRunner)
- [x] 3 Support object? type by KernelPromptTemplate
```
