### ISSUE TITLE
.Net OpenAI Support for Tools / Tool Calling

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#4101]
Inner Issues needed accomplish this requirement.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/4102
- [ ] .Net OpenAI Support for Tools - Adapts FunctionCallBehavior abstractions
- [ ] .Net OpenAI Support for Tools - Swithc OpenAI Planner to use Tools
- [ ] .Net OpenAI Support for Tools - Switch all samples to use Tools
- [ ] .Net OpenAI Support for Tools - Drop support for legacy function calling
```
