### ISSUE TITLE
.Net: SK Public API review

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#4269]
```[tasklist]
### Tasks
- [ ] ~~Move `HandlebarsKernelExtensions` class to the `Microsoft.SemanticKernel.PromptTemplates.Handlebars` namespace. (Sergey)~~
- [x] Add `CancellationToken` parameter to the `HandlebarsKernelExtensions.InvokeHandlebarsPromptAsync` method.  (Sergey)
- [x] Make the `AzureOpenAITextToImageResponse` internal. (Dmytro)
- [ ] ~~nit: The `ParameterType` property of the `OpenAIFunctionParameter`, `OpenAIFunctionReturnParameter`, `KernelParameterMetadata`, etc... classes can be renamed to `Type` to be aligned with other properties - `Name`, `Description`, etc (Dmytro)~~
- [x] Remove `TextEmbeddingRequest`, `OpenAITextEmbeddingRequest` and `AzureOpenAITextEmbeddingRequest` classes from the `Microsoft.SemanticKernel.Connectors.OpenAI` namespace (Dmytro)
- [x] Add `CancellationToken` to the `KernelExtensions.InvokePromptAsync` method  (Sergey)
- [x] Consider changing `InputVariable.Default` property type from string to object? (Sergey)
- [x] Remove `ChatHistory.Add` method since there's already `ChatHistory.AddMessage` one (Dmytro)
- [x] Align names of parameters of `ChatMessageContent` type methods. In some cases, the parameter named `...content`, in tother `item` (Dmytro)
- [x] Move `HttpOperationException` from `Microsoft.SemanticKernel.Http` to `Microsoft.SemanticKernel` (Dmytro)
```

**Comment by stephentoub** [comment]
This was completed
