### ISSUE TITLE
.Net GoogleAI connector progress (Gemini)

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#4680]
### Motivation and Context

https://github.com/microsoft/semantic-kernel/issues/4334

### Description

Progress of implementation of Google Gemini connector.
Current implementation [GEMINI BRANCH](https://github.com/microsoft/semantic-kernel/tree/feature-connectors-gemini)

### TODO

1. TextGenerationService

- [x] Get text (#4742)
    - [x] Create examples (#4873)
- [x] Stream text (#4742)
    - [x] Create examples (#4873)
- [x] Add DI extensions (#4766)
- [x] Provide metadata from response
- [x] Function calling (#5044)
    - [x] Create examples

2. ChatCompletionService

- [x] Get text (#4742)
    - [x] Create examples (#4873)
- [x] Stream text (#4742)
    - [x] Create examples (#4873)
- [x] Add DI extensions (#4766)
- [x] Provide metadata from response (#4677)
- [x] Function calling (#5044)
- [x] Pass images with prompt (#4957) (#5105)

3. Others
- [x] Embeddings (#4745, #4758, #4786)
- [x] Counting tokens (added without public service) (#4677)
- [x] Vertex AI implementation
- [x] Logging
- [x] Telemetry

Notes:
- Token count in a metadata is provided only for the VertexAI, for the GoogleAI is zero,
- System messages are not supported by gemini models. If a chat history contains only one system message, it will be converted to the user message. If there are more than one system message an exception will be thrown.
- GoogleAI isn't available in the GDPR countries. If you want to use gemini in these countries, you need vpn or use VertexAI which works.
- VertexAI supports gemini-vision via both an URI and a BinaryData, GoggleAI supports only BinaryData. When you pass an image as URI you need to pass a mime_type as an ImageContent.MimeType.

Tested models:
1. GoogleAI
    - gemini-pro (text/chat generation/stream)
    - gemini-pro-vision (chat generation/stream with vision capability) (binary data only)
    - embedding-001 (embeddings)
2. VertexAI
    - gemini-pro (text/chat generation/stream)
    - gemini-pro-vision (chat generation/stream with vision capability)
    - textembedding-gecko (embeddings)

**Comment by SavoInfostream** [comment]
@Krzysztof318  Thanks for the info. Is an alpha nuget  going to be available before, maybe?

**Comment by Krzysztof318** [comment]
@SavoInfostream I don't think so. If you want to do some tests with gemini clone branch and generate nugets yourself.

**Comment by AshD** [comment]
@Krzysztof318  How do I set the Safety settings in Gemini Connector. 

I tried this 
```
var geminiRequestSettings = new GeminiPromptExecutionSettings();
geminiRequestSettings.SafetySettings = new List<GeminiSafetySetting>() { new GeminiSafetySetting(GeminiSafetyCategory.Unspecified, GeminiSafetyThreshold.BlockNone) };
```
and it starting throwing HTTP 400 errors. Removing the SafetySettings line and everything works.

Thanks,
Ash

**Comment by Krzysztof318** [comment]
@AshD you can't use this category and block none as a query. There is no possibility to disable safety mechanism in gemini. You can only make safety mechanism more sensitive.

**Comment by AshD** [comment]
I am getting the safety error **randomly** for the following prompt - Tell me a interesting fact about Barack Obama not exceeding 280 characters"

Is the default (not specifying the safety) the lowest safety settings? Thanks

**Comment by Krzysztof318** [comment]
@AshD honestly Gemini has very unfriendly moderation, it refuses to answer often. Additionaly I have noticed that Gemini was ignoring  prompt like not exceeding 280 characters in my tests but it's not a rule.

Yep, default safety settings are lowest...

**Comment by AshD** [comment]
Thanks Krzysztof.

The model is not very useful if it randomly kicks in safety settings for
the same prompt.

**Comment by Krzysztof318** [comment]
Gemini branch was merged to main.

**Comment by AshD** [comment]
Thanks @Krzysztof318 I tested the alpha version of the Nuget package and it works fine in a WPF app :-)

This might be a bit outside the use case for this library but trying it out in a Blazor Webassembly app throws a CORS error. The official Google Javascript SDK uses a HTTP POST and other HTTP headers to avoid this. 
https://ai.google.dev/tutorials/get_started_web

**Comment by Krzysztof318** [comment]
Hi @AshD if you think this problem is related to connector implementation, please rise a new issue in repo and cc me.

**Comment by AshD** [comment]
Done. Thanks for the quick reply.
https://github.com/microsoft/semantic-kernel/issues/5915

**Comment by apipino** [comment]
- I'm using Google connector 'AddGoogleAIGeminiChatCompletion'
- I'm uploading 'd:\image.jpg' with 'Google AI Media-Upload'. ref.: "https://ai.google.dev/api/files"
- for example I am getting 'uri' = "https://generativelanguage.googleapis.com/v1beta/files/qsv8wazc13qj"
- when use: "chatHistory.AddUserMessage(New ChatMessageContentItemCollection From {New TextContent('ask'), New ImageContent(New Uri('imgUri'))})"
	Exception ex.Message = "Image content 'MimeType' is empty."

has no option ImageContent(uri, mimeType) (?)
