### ISSUE TITLE
.Net: [Agents] SK agents abstraction

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#4824]
```[tasklist]
### Tasks
- [x] Add the KernelAgent abstract class.
- [x] Identify data contract for the InvokeAsync method - ChatMessageContent vs AgentMessage (OpenAI Assistant API has Citations)
- [x] Add InvokeAsync to the KernelAgent abstract class.
- [x] Inherit ChatCompletionAgent from the KernelAgent class.
- [x] Clarify the following requirements: 1.Pass OpenAI Assistant API Thread from message to agent. Is it needed? Which scenarios? 2. ChatHistory vs AgentHistory
```
