### ISSUE TITLE
.Net: Function Calling Abstractions

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5253]
```[tasklist]
### Tasks
- [x] Explore current function-calling model implementation & usage.
- [x] POC to understand the scope, feasibility, etc.
- [x] Share POC details to have every one of the same page and collect feedback.
- [x] Implement the abstraction taking into account the feedback for OpenAI connector only.
```

**Comment by Krzysztof318** [comment]
I recommend looking at the implementation in gemini, it will make it easier to extract the abstraction, I tried to make it as similar as possible to openai's connector. https://github.com/microsoft/semantic-kernel/pull/5044
