### ISSUE TITLE
.Net Anthropic connector progress (Claude 3)

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#5690]
Progress of implementation of Anthropic Claude 3 family connector.
Current implementation /here put branch link/

### TODO

1. ChatCompletionService

- [ ] Get chat
    - [ ] Create examples
- [ ] Stream chat
    - [ ] Create examples
- [ ] Add DI extensions
- [ ] Provide metadata from response
- [ ] Function calling
    - [ ] Create examples
- [ ] Pass images with prompt

2. Others
- [ ] Logging
- [ ] Telemetry

**Comment by Krzysztof318** [comment]
Bump

**Comment by Pekket** [comment]
Any update on this? @RogerBarreto

**Comment by Krzysztof318** [comment]
@Pekket I hold with developing connector until function calling abstraction will be ready. But probably fca won't be ready fast, so yesterday we decided with @RogerBarreto to deploy connector now without fc functionality. I am working currently on connector code.

**Comment by Pekket** [comment]
@Krzysztof318 Thanks for the work, looks good 🦸 
Any idea when the stream chat will be implemented?

**Comment by Krzysztof318** [comment]
@Pekket soon but before we merge claude to main brach I think it will take couple of weeks.

**Comment by rodion-m** [comment]
@Krzysztof318 We’re so excited for it.

**Comment by celsound** [comment]
Hear hear! Claude support please!

**Comment by payoff** [comment]
There is any update?

**Comment by Krzysztof318** [comment]
Sorry, I have much work last time, but I started working on streaming. I hope I will publish PR this week.

**Comment by payoff** [comment]
I wanted to check in and see if there are any updates on the current development status. Specifically, I would like to know if there is an estimated date when the ongoing work will be merged into the master branch.

Thank you for your time and support.
Mik

**Comment by Krzysztof318** [comment]
@payoff I hope soon, currently I am waiting for review latest PR.

**Comment by therealpaulgg** [comment]
> @payoff I hope soon, currently I am waiting for review latest PR.

Looks like 2 unit tests are failing?

**Comment by kcrandall** [comment]
Any plans to support prompt caching at some point?

https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

**Comment by lostmsu** [comment]
Is this up to date? Does the lack of function calling mean we can't use the new computer tool?

**Comment by nonoc** [comment]
Hi guys, I'm having a hard time finding a way to connect to Anthropic. It's something that's actually implemented in the latest versions of SemanticKernel. I'm currently working with version 1.72, which is the most stable, using KernelFactory. I don't really know why higher versions don't work with KernelFactory, and with Anthropic I have a connection error. It's something that's being tested. 
Thank you all very much.

**Comment by lostmsu** [comment]
@nonoc Funny you ask, I started implementing computer use tool off where this work was stopped, have prototype here: https://github.com/BorgGames/semantic-kernel/tree/AnthropicTools

Beta package is here: https://www.nuget.org/packages/Lost.SemanticKernel.Connectors.Anthropic/1.22.0-alpha0

### Usage
```csharp
var chatHistory = new ChatHistory();
chatHistory.AddUserMessage("Open Notepad and type Hi!");

var sut = new AnthropicChatCompletionService(this.AnthropicGetModel(), this.AnthropicGetApiKey(), new(beta: ComputerUse_2024_10_22.Beta));

var kernel = new Kernel();
kernel.Plugins.Add(ComputerUse_2024_10_22.ComputerPlugin(NoOpComputer.Instance));

// Act
var response = await sut.GetChatMessageContentsAsync(chatHistory, kernel: kernel);

// Assert
var lastMessage = response[^1];
var metadata = lastMessage.Metadata as AnthropicMetadata;
Assert.NotNull(metadata);
this.Output.WriteLine($"FinishReason: {metadata.FinishReason}");
Assert.Equal(AnthropicFinishReason.ToolUse, metadata.FinishReason);

var supposedlyScreenshotCall = lastMessage.Items
    .OfType<FunctionCallContent>()
    .FirstOrDefault();
Assert.NotNull(supposedlyScreenshotCall);
Assert.Equal("computer", supposedlyScreenshotCall.FunctionName);
if (supposedlyScreenshotCall.Arguments?["action"] is not JsonElement action)
{
    Assert.Fail("action is not supplied or wrong type");
    return;
}
Assert.Equal("screenshot", action.Deserialize<string>());
```

**Comment by mhensen** [comment]
Any updates? really looking formward to use anthropic in my projects..

**Comment by lostmsu** [comment]
Just updated the alpha to the latest official release 1.25.0, and enabled an option to auto execute tools.

https://www.nuget.org/packages/Lost.SemanticKernel.Connectors.Anthropic/1.25.0-alpha2#readme-body-tab

**Comment by Krzysztof318** [comment]
@lostmsu hi, nice to see you are working also on this connector. But instead of creating own repo could you contribute to anthropic branch and create PR in SK?

**Comment by lostmsu** [comment]
@Krzysztof318 sure, I didn't notice the branch until recently.

**Comment by therealpaulgg** [comment]
@Krzysztof318 have you tested on Google vertex? For me earlier I was having issues unless I made changes, which I commented on your PR.

**Comment by nonoc** [comment]
Why we need to use .NET Standard 2.0 to use it?

**Comment by Krzysztof318** [comment]
@glanik it will, PR is waiting for final review. AI.extensions is designed to integration with existing .net sdk of model providers. But anthropic doesn't have .net sdk.

**Comment by Millmer** [comment]
I noticed that the related PR (https://github.com/microsoft/semantic-kernel/pull/7364) to introduce Anthropic support for C# was recently closed. Could you clarify what this means for the expected timeline for supporting Anthropic models in C# independently of Bedrock?

**Comment by RogerBarreto** [comment]
This PR was closed after `Microsoft.Extensions.AI.IChatClient` abstractions were introduced, and became supported in the C# ecosystem, where you can convert a `IChatClient` to a `SK.IChatCompletionService` transparently. 

In a near future such conversion will not be needed and you will be able to use `IChatClient`s directly with `Kernel`. 

We already have `IChatClient` implementations of Anthropic in the community and following, we encourage the community growth by pointing towards those implementations instead of centralizing all the support on our repository.

For reference if you want to use Anthropic directly with SK you can go for: 

[https://github.com/tghamm/Anthropic.SDK](https://github.com/tghamm/Anthropic.SDK)

And use a implementation like:

```csharp
using Microsoft.SemanticKernel;

var skChatService = new AnthropicClient().Messages.AsChatCompletionService();

// OR

var builder = Kernel.CreateBuilder();
builder.Services.AddTransient<IChatCompletionService>((sp) => new AnthropicClient().Messages.AsChatCompletionService());
```
