### ISSUE TITLE
.Net: Support XML Tags in Chat Prompts

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5699]
Change the prompt rendering behavior to require opt-in to allow message tags to be inserted using variables or function calls

### Tasks
- [x] Create an ADR describing the new behaviour
- [x] Implement support for developers to allow unsafe input variables
- [x] Implement support for developers to allow unsafe function calls
- [x] Implement support for developers to revert to the old behaviour
```
