### ISSUE TITLE
.Net: ADR for Text Search Service Abstraction

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5799]
```[tasklist]
### Tasks
- [x] Implement abstraction for Azure AI Search
- [x] Implement abstraction for Bing Search
- [x] Implement abstraction for Google Search
- [x] Implement abstraction for Vector DB
- [x] Show how to configure multiple plugins with the same search service
- [x] Investigate approach to support common features such as paging, sorting, filtering, ...
- [x] Create an ADR describing the new Text Search abstraction
```
