### ISSUE TITLE
Python: Built in support for Open Telemetry

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#5891]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/issues/8285
- [ ] https://github.com/microsoft/semantic-kernel/issues/8371
- [ ] https://github.com/microsoft/semantic-kernel/issues/8373
- [ ] https://github.com/microsoft/semantic-kernel/issues/8374
- [ ] https://github.com/microsoft/semantic-kernel/issues/8375
- [ ] https://github.com/microsoft/semantic-kernel/issues/8411
- [ ] https://github.com/microsoft/semantic-kernel/issues/8412
```

**Comment by moonbox3** [comment]
I've been looking at https://opentelemetry.io/docs/languages/python/instrumentation/ and I am not sure what would be considered a breaking change? We could implement metrics/traces as opt-in behavior.

**Comment by TaoChenOSU** [comment]
> I've been looking at https://opentelemetry.io/docs/languages/python/instrumentation/ and I am not sure what would be considered a breaking change? We could implement metrics/traces as opt-in behavior.

Most of the model diagnostics features (OTeL GenAI semantic convention related code) will be considered experimental.
