### ISSUE TITLE
.Net: Samples Restructuring

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5949]
Implement a more intuitive and discoverable structure for our samples

### Tasks
- [x] Create an ADR describing the sample structure (this is to be applied to all languages)
- [x] Review ADR and get agreement on the sample structure
- [x] Refactor .Net samples to adhere to the new structure
- [ ] Adjust Concepts Namespaces (Test Explorer) and Readme.md 
```
