### ISSUE TITLE
Use standardized vocabulary and specification for observability in Semantic Kernel

### ISSUE THREAD

**Issue by TaoChenOSU** [microsoft/semantic-kernel#6161]
Our goal is to make sure that SK provides the best developer experience while complying with the industry standards for observability in generative-AI-based applications.

ADR: https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0044-OTel-semantic-convention.md
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/semantic-kernel/pull/6150
- [ ] https://github.com/microsoft/semantic-kernel/issues/6174
- [ ] https://github.com/microsoft/semantic-kernel/issues/6175
- [ ] https://github.com/microsoft/semantic-kernel/issues/6176
- [ ] https://github.com/microsoft/semantic-kernel/issues/6189
- [ ] https://github.com/microsoft/semantic-kernel/issues/6489
```

**Comment by TaoChenOSU** [comment]
This is an ongoing effort to align SK to the latest semantic conventions as best as we can. The GenAI semantic conventions are still under development and rapidly evolving. We will keep an eye on the following items:
1. Metrics
2. Vector database conventions
3. Conventions for multi-modality

**Comment by markwallace-microsoft** [comment]
Closing as stale
