### ISSUE TITLE
.Net: Retire OpenAI plugins functionality

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#6881]
Obsolete OpenAI plugins functionality https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Functions/Functions.OpenApi/OpenAI.

```[tasklist]
### Tasks
- [x] Mark all OpenAI plugins as obsolete.
- [x] Release the changes.
- [x] Remove the obsolete code.
```
