### ISSUE TITLE
.Net OpenAI V2 Migration Steps Tracking

### ISSUE THREAD

**Issue by RogerBarreto** [microsoft/semantic-kernel#6916]
Epic Issue
- #6868 

OpenAI V2 - Next steps (Dependencies and tests included for each)

- [x] Create and move shared utilities for both azure and openai connectors.
    - #6915
    - Related comment:  https://github.com/microsoft/semantic-kernel/pull/6906#discussion_r1649270971
- [x] Implement TextToImage Service 
- [x] Implement AudioToText Service
- [x] Implement TextToAudio Service
- [x] Files Service
- [x] ChatCompletion Service Without Function Calling
- [x] ChatCompletion With Function Calling
