### ISSUE TITLE
.Net: Migrate to OpenAPI.Net v2 SDK

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#9832]
- [x] Create OpenAPI v2 branch - https://github.com/microsoft/semantic-kernel/tree/openapi-v2
- [x] Reference the latest OpenAPI.NET v2 SDK nuget package - https://github.com/microsoft/OpenAPI.NET
- [x] Refactor the code to use the new OpenAPI.NET SDK public API surface
- [ ] Handle OpenAPI document format in SK - https://github.com/microsoft/semantic-kernel/issues/9857
- [ ] Handle OpenAPI document format in ApiManifest and CopilotAgentPlugin - https://github.com/microsoft/semantic-kernel/issues/9859
- [ ] Remove version downgrading functionality - https://github.com/microsoft/semantic-kernel/issues/9860
- [ ] Update documentation
